[package]
name = "inori"
version = "0.1.0"
authors = ["inori-lover <337938188@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
